version: '3'
services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src:/workspace/src
      - ./pom.xml:/workspace/pom.xml
  db:
    image: mysql:8
    container_name: springboot-db
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./docker/db/data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: springboot-phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=user
      - PMA_PASSWORD=root
    ports:
      - 3000:80
    volumes:
      - ./docker/phpmyadmin/sessions:/session
    depends_on:
      - db